### PR TITLE
Use NO_VALIDATION

### PR DESCRIPTION
**Pull request by martinwork**
https://github.com/lancaster-university/codal-microbit-v2/issues/134

### CODE REVIEW

**Comment by finneyj** [comment]
Thanks martin. 

I was just looking at this too.  Feels like this is the correct thing to do, so that we align with the behaviour here:
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/bluetooth/MicroBitPartialFlashingService.cpp#L298

Do you know if the CRC is checked before a reboot happens though? if we do this, are we opening ourselves to other possible fail cases? (BLE flash crashes mid way etc) ?

**Comment by finneyj** [comment]
@martinwork  @microbit-carlos  might also want to track this.

**Comment by martinwork** [comment]
I was just checking this too. I just remembered this might be used to signify that the image size is not valid, so dual bank DFUs are not possible (as they aren't after a USB or partial flash). I believe the image downloaded is checked against the hash in the init packet and the CRC is calculated on the received image, so a CRC check at the end of download is not a big thing.

**Comment by martinwork** [comment]
Here: https://github.com/microbit-foundation/v2-bootloader/blob/master/nRF5SDK_mods/components/libraries/bootloader/dfu/nrf_dfu_validation.c#L594

**Comment by finneyj** [comment]
Right. We don't support the dual bank flashing algorithm anyway do we?

**Comment by finneyj** [comment]
...and the business end seems to be here?

https://github.com/microbit-foundation/v2-bootloader/blob/master/nRF5SDK_mods/components/libraries/bootloader/dfu/nrf_dfu_validation.c#L852

**Comment by finneyj** [comment]
OK - seems like this path is the way to go then. Thanks @martinwork!

Do you have the toolchain to build this and raise a PR to get the binary in codal-microbit-v2? I don't think i've ever built the bootloader...

**Comment by microbit-carlos** [comment]
We have setup CircleCi to build the bootloader in a container and upload the output to circle CI artefact, so once it's merged and ready to go I can create a GitHub release and upload the bootloader and container.

**Comment by finneyj** [comment]
Sounds good - thanks @microbit-carlos.

I'm happy for this to go in @martinwork - assume you still are?

**Comment by microbit-carlos** [comment]
I'm not sure why CircleCi is not triggering for this PR, it did for https://github.com/microbit-foundation/v2-bootloader/pull/16 and the [config file](https://github.com/microbit-foundation/v2-bootloader/blob/master/.circleci/config.yml) doesn't filter out events. And the status page indicates all is working: https://status.circleci.com
Weird

**Comment by martinwork** [comment]
Thanks @microbit-carlos . I was just about to say that I think there's a system now!

Dual bank has been possible after a DFU, but not after a USB flash, because of the fixed "no validation" settings pages, or more recently after a partial flash.

I'm happy if making it consistent is preferable.

**Comment by martinwork** [comment]
> ...and the business end seems to be here?
> 
> https://github.com/microbit-foundation/v2-bootloader/blob/master/nRF5SDK_mods/components/libraries/bootloader/dfu/nrf_dfu_validation.c#L852

Yes, that's at the end of a DFU, where the CRC that would be validated is calculated from the downloaded image. So it's only a check against future flash corruptions.

**Comment by finneyj** [comment]
right - that's what I thought @martinwork. 

Ok - let's see if the CI fires up.

**Comment by microbit-carlos** [comment]
Bootloader build uploaded to the v1.1.0 release: https://github.com/microbit-foundation/v2-bootloader/releases/tag/v1.1.0

**Comment by finneyj** [comment]
great - thanks @microbit-carlos!

@martinwork - can you test the new .o file in a CODAL build to verify it fixes the bug? If so, we can merge and tag this into codal-microbit-v2 as a minor change...

**Comment by martinwork** [comment]
I already tested the change in a simple C++ hello world. I have copied the bootloader.o from https://github.com/microbit-foundation/v2-bootloader/releases/tag/v1.1.0 and built the sample sample. It DFUs over itself OK

BLE flashing over an old hex will still have the problem. I think the apps can overcome that by using a full Nordic init packet instead of the simple one. I am looking at this now.

**Comment by finneyj** [comment]
perfect - many thanks @martinwork.

I'll merge the new bootloader into codal-microbit-v2 and tag so that we can end to end test in due course.

**Comment by microbit-carlos** [comment]
Thanks for all the work Martin!

> BLE flashing over an old hex will still have the problem. I think the apps can overcome that by using a full Nordic init packet instead of the simple one. I am looking at this now.

If this is something that the Android app will need as well could you email this info to Jonny as well?

**Comment by martinwork** [comment]
@microbit-carlos Yes. I started to work on this last year. Will C be usable in the android app?

It will be most useful if we can release updates soon, or everyone will have hit the problem and updated the bootloader via USB anyway.

**Comment by martinwork** [comment]
@microbit-carlos @jaustin Email sent.

**Pull request merged**
